#!/usr/bin/env python3
"""
build_bib.py -- assembles references.bib for the revised manuscript.

Takes every key cited in main.tex and in the generated tables, pulls the
matching entry from the original bibliography or from the four verified
new-reference files, and writes a single trimmed references.bib containing
exactly the cited entries and nothing else. Reports any key that cannot be
resolved, so an undefined citation is caught before compilation.
"""
import re, os, sys, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def parse_bib(txt):
    entries, i = [], 0
    while True:
        m = re.search(r'@(\w+)\s*\{\s*([^,\s]+)\s*,', txt[i:])
        if not m:
            break
        start = i + m.start()
        b = txt.index('{', start)
        depth, j = 0, b
        while j < len(txt):
            if txt[j] == '{':
                depth += 1
            elif txt[j] == '}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        entries.append((m.group(2), txt[start:j + 1]))
        i = j + 1
    return entries


def cited_keys():
    files = [os.path.join(ROOT, 'main.tex')] + \
            sorted(glob.glob(os.path.join(ROOT, 'tables', '*.tex')))
    keys = set()
    for f in files:
        tex = open(f, encoding='utf-8').read()
        for m in re.finditer(r'\\cite[tp]?\*?\{([^}]*)\}', tex):
            for k in m.group(1).split(','):
                k = k.strip()
                if k:
                    keys.add(k)
    return keys


def main():
    pool = {}
    order = []
    # new, verified references take precedence over the legacy file
    for f in ['data/newrefs_A.bib', 'data/newrefs_B.bib',
              'data/newrefs_C.bib', 'data/newrefs_D.bib']:
        for k, raw in parse_bib(open(os.path.join(ROOT, f),
                                    encoding='utf-8', errors='ignore').read()):
            pool.setdefault(k, raw)
    for k, raw in parse_bib(open(os.path.join(ROOT,
                                              'references_original.bib'),
                                 encoding='utf-8', errors='ignore').read()):
        pool.setdefault(k, raw)

    keys = cited_keys()
    resolved, missing = [], []
    for k in sorted(keys):
        if k in pool:
            resolved.append((k, pool[k]))
        else:
            missing.append(k)

    header = (
        '%% ====================================================================\n'
        '%% references.bib\n'
        '%% Bibliography for "Artificial Intelligence-Driven Forecasting of\n'
        '%% Relief Demand in Emergency Supply Chains: A PRISMA-ScR Scoping\n'
        '%% Review of Research Attention and Evidence of Efficacy"\n'
        '%%\n'
        '%% Contains exactly the %d entries cited in the manuscript and its\n'
        '%% tables. Entries added at revision carry a %% VERIFIED-AT: comment\n'
        '%% recording the indexer or publisher record against which the\n'
        '%% bibliographic fields were checked.\n'
        '%% Generated by code/build_bib.py -- do not edit by hand.\n'
        '%% ====================================================================\n\n'
        % len(resolved))
    with open(os.path.join(ROOT, 'references.bib'), 'w',
              encoding='utf-8') as fh:
        fh.write(header)
        for k, raw in resolved:
            fh.write(raw.rstrip() + '\n\n')

    print('cited keys      : %d' % len(keys))
    print('resolved        : %d' % len(resolved))
    print('UNRESOLVED      : %d' % len(missing))
    for k in missing:
        print('   MISSING: %s' % k)
    return 1 if missing else 0


if __name__ == '__main__':
    sys.exit(main())
