#!/usr/bin/env python3
"""
make_xref.py -- reads main.aux and writes response/xref.tex, a set of LaTeX
macros giving the printed number of every section, figure and table in the
compiled manuscript.

The response-to-reviewers letter cites those numbers through these macros
rather than typing them, so the letter cannot point a reviewer at the wrong
section if the manuscript is recompiled and the numbering shifts.
"""
import re, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUX = os.path.join(ROOT, 'main.aux')
OUT = os.path.join(ROOT, 'response', 'xref.tex')

# label -> macro name (letters only, as LaTeX requires)
MAP = {
    'sec:introduction': 'SecIntro', 'sec:questions': 'SecQuestions',
    'sec:priorreviews': 'SecPrior', 'sec:methods': 'SecMethods',
    'sec:protocol': 'SecProtocol', 'sec:eligibility': 'SecEligibility',
    'sec:search': 'SecSearch', 'sec:selection': 'SecSelection',
    'sec:charting': 'SecCharting', 'sec:denominators': 'SecDenominators',
    'sec:appraisal': 'SecAppraisal',
    'sec:synthesisapproach': 'SecSynthApproach',
    'sec:reproducibility': 'SecRepro', 'sec:background': 'SecBackground',
    'sec:rdf': 'SecRdf', 'sec:ai': 'SecAi',
    'sec:traditional': 'SecTraditional', 'sec:commercial': 'SecCommercial',
    'sec:pipeline': 'SecPipeline', 'sec:synthesis': 'SecSynthesis',
    'sec:fam_stat': 'SecFamStat', 'sec:fam_kb': 'SecFamKb',
    'sec:fam_ml': 'SecFamMl', 'sec:fam_dl': 'SecFamDl',
    'sec:fam_genai': 'SecFamGenai', 'sec:fam_optsim': 'SecFamOptsim',
    'sec:crosstab': 'SecCrosstab', 'sec:turnover': 'SecTurnover',
    'sec:mapping': 'SecMapping', 'sec:growth': 'SecGrowth',
    'sec:geography': 'SecGeography', 'sec:outlets': 'SecOutlets',
    'sec:objectives': 'SecObjectives', 'sec:hazards': 'SecHazards',
    'sec:paradigm': 'SecParadigm', 'sec:efficacy': 'SecEfficacy',
    'sec:howmuch': 'SecHowmuch', 'sec:whatreport': 'SecWhatreport',
    'sec:degradation': 'SecDegradation', 'sec:claims': 'SecClaims',
    'sec:bottlenecks': 'SecBottlenecks',
    'sec:datascarcity': 'SecDatascarcity',
    'sec:infrastructure': 'SecInfra', 'sec:governance': 'SecGovernance',
    'sec:quality': 'SecQuality', 'sec:capability': 'SecCapability',
    'sec:future': 'SecFuture', 'sec:futuredirections': 'SecFutureDir',
    'sec:emergingtrends': 'SecEmerging', 'sec:managerial': 'SecManagerial',
    'sec:limitations': 'SecLimitations', 'sec:conclusion': 'SecConclusion',
    'fig:escm': 'FigEscm', 'fig:prisma': 'FigPrisma',
    'fig:workflow': 'FigWorkflow', 'fig:methods': 'FigMethods',
    'fig:heatmap': 'FigHeatmap', 'fig:overtime': 'FigOvertime',
    'fig:year': 'FigYear', 'fig:authorgeo': 'FigAuthorgeo',
    'fig:focusgeo': 'FigFocusgeo', 'fig:outlets': 'FigOutlets',
    'fig:objectives': 'FigObjectives', 'fig:disaster': 'FigDisaster',
    'fig:paradigm': 'FigParadigm', 'fig:linearity': 'FigLinearity',
    'fig:evidence': 'FigEvidence',
    'tab:search_strategy': 'TabSearch', 'tab:coding_rules': 'TabCoding',
    'tab:commercial_mapping': 'TabMapping',
    'tab:method_by_disaster': 'TabMethodHazard',
    'tab:efficacy': 'TabEfficacy', 'tab:included_studies': 'TabIncluded',
}


def main():
    if not os.path.exists(AUX):
        sys.exit('main.aux not found: compile the manuscript first')
    aux = open(AUX, encoding='utf-8', errors='ignore').read()
    num = {}
    for m in re.finditer(r'\\newlabel\{([^}]+)\}\{\{([^}]*)\}\{(\d+)\}', aux):
        num[m.group(1)] = (m.group(2), m.group(3))

    lines = ['% AUTO-GENERATED by code/make_xref.py from main.aux.\n',
             '% Numbers below are the printed section/figure/table numbers of\n',
             '% the compiled manuscript. Do not edit by hand.\n\n']
    missing = []
    for lab, mac in MAP.items():
        if lab in num:
            n, page = num[lab]
            lines.append('\\newcommand{\\%s}{%s}\n' % (mac, n))
            lines.append('\\newcommand{\\%sPage}{%s}\n' % (mac, page))
        else:
            missing.append(lab)
            lines.append('\\newcommand{\\%s}{??}\n' % mac)
            lines.append('\\newcommand{\\%sPage}{??}\n' % mac)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w').writelines(lines)
    print('wrote %s with %d cross-references' % (
        os.path.relpath(OUT, ROOT), len(MAP)))
    if missing:
        print('WARNING: labels not found in main.aux:')
        for lab in missing:
            print('   %s' % lab)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
